In [95]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [96]:
data=pd.read_csv(r'C:\Users\divya\Documents\GitHub\Deep-Learning-Repository\Neural_Nets\Churn_Modelling.csv')

In [97]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [98]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [99]:
data.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [100]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [101]:
data.drop(labels=["RowNumber","CustomerId","Surname"],axis=1,inplace=True)

In [102]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [103]:
data.duplicated().sum()

np.int64(0)

In [104]:
data.Geography.value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [106]:
y=data[["Exited"]]
X=data.drop(labels="Exited",axis=1)

In [107]:
y.value_counts()

Exited
0         7963
1         2037
Name: count, dtype: int64

In [108]:
cat_variables=[]
num_variables=[]
for i in X.columns:
    if X[i].dtype=="object":
        cat_variables.append(i)
    else:
        num_variables.append(i)

In [109]:
num_variables

['CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary']

In [110]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [111]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler

preprocessor=ColumnTransformer([
    ("encoder" , OneHotEncoder(drop='first'),cat_variables),
    ("scaler",StandardScaler(),num_variables)
])

In [112]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [113]:
feature_names = preprocessor.get_feature_names_out()
feature_names

array(['encoder__Geography_Germany', 'encoder__Geography_Spain',
       'encoder__Gender_Male', 'scaler__CreditScore', 'scaler__Age',
       'scaler__Tenure', 'scaler__Balance', 'scaler__NumOfProducts',
       'scaler__HasCrCard', 'scaler__IsActiveMember',
       'scaler__EstimatedSalary'], dtype=object)

In [114]:
X_train_df = pd.DataFrame(X_train,
    columns=feature_names
)

In [115]:
X_test_df = pd.DataFrame(X_test,
    columns=feature_names
)

In [116]:
X_train=X_train_df
X_test=X_test_df

In [117]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

lr=LogisticRegression()
param={
    'C':[1,10,100,100],
    'solver':['lbfgs','linear','rbf'],
    'penalty':['l1','l2'],
    'max_iter':[1000],
    'class_weight':[
        {0:0.63,2:2.46},
        {0:1,1:10},
        {0:0.3,1:0.7}
    ]
}
grid=GridSearchCV(estimator=lr,param_grid=param)

In [118]:
grid.fit(X_train,y_train)

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 100, 100],
                         'class_weight': [{0: 0.63, 2: 2.46}, {0: 1, 1: 10},
                                          {0: 0.3, 1: 0.7}],
                         'max_iter': [1000], 'penalty': ['l1', 'l2'],
                         'solver': ['lbfgs', 'linear', 'rbf']})

In [119]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

y_pred=grid.predict(X_test)
acc=accuracy_score(y_test,y_pred)
acc

0.7895

In [120]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1368  225]
 [ 196  211]]

In [121]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.86      0.87      1593
           1       0.48      0.52      0.50       407

    accuracy                           0.79      2000
   macro avg       0.68      0.69      0.68      2000
weighted avg       0.80      0.79      0.79      2000

In [122]:
grid.best_estimator_

LogisticRegression(C=1, class_weight={0: 0.3, 1: 0.7}, max_iter=1000)

In [123]:
from sklearn.tree import DecisionTreeClassifier

dt=DecisionTreeClassifier(criterion="gini")
dt.fit(X_train,y_train)
y_pred=dt.predict(X_test)
acc=accuracy_score(y_test,y_pred)

In [124]:
acc

0.7895

In [125]:
import tensorflow as tf

In [126]:
from tensorflow.keras.models import load_model,Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.metrics import Accuracy
from tensorflow.keras.optimizers import SGD

In [127]:
model=Sequential([
    Dense(64,input_shape=(X_train.shape[1],), activation="relu"),
    Dense(32,activation="relu"),
   Dense (1,activation="sigmoid")
])

In [128]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,881 (11.25 KB)

 Trainable params: 2,881 (11.25 KB)

 Non-trainable params: 0 (0.00 B)

In [129]:
model.compile(optimizer="SGD",loss="BinaryCrossentropy",metrics=['accuracy'])
import datetime

In [130]:
log_dir="logs/fit/"

In [131]:
from tensorflow.keras.callbacks import TensorBoard

tensorboard=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [132]:
from tensorflow.keras.callbacks import EarlyStopping

stopping=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [133]:
history=model.fit(X_train,y_train,
                  validation_data=(X_test,y_test),batch_size=64,
                  epochs=100,
                  callbacks=[stopping,tensorboard])

Epoch 1/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7716 - loss: 0.5822 - val_accuracy: 0.7965 - val_loss: 0.4902
Epoch 2/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7964 - loss: 0.4848 - val_accuracy: 0.7965 - val_loss: 0.4618
Epoch 3/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8045 - loss: 0.4524 - val_accuracy: 0.7965 - val_loss: 0.4452
Epoch 4/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7984 - loss: 0.4524 - val_accuracy: 0.8040 - val_loss: 0.4340
Epoch 5/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7959 - loss: 0.4483 - val_accuracy: 0.8075 - val_loss: 0.4261
Epoch 6/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8071 - loss: 0.4274 - val_accuracy: 0.8110 - val_loss: 0.4205
Epoch 7/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8179 - loss: 0.4233 - val_accuracy: 0.8085 - val_loss: 0.4159
Epoch 8/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8126 - loss: 0.4311 - val_accuracy: 0.8110 - val_loss: 0.4122
Epoch 9/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8226 - loss: 0.4157 - val_accuracy: 0.8170 - val_loss: 0.4089
Epoch 10/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8190 - loss: 0.4201 - val_accuracy: 0.8190 - val_loss: 0.4059
Epoch 11/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8227 - loss: 0.4050 - val_accuracy: 0.8225 - val_loss: 0.4031
Epoch 12/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8283 - loss: 0.3994 - val_accuracy: 0.8245 - val_loss: 0.4002
Epoch 13/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8245 - loss: 0.4046 - val_accuracy: 0.8255 - val_loss: 0.3976
Epoch 14/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8231 - loss: 0.4023 - val_accuracy: 0.8275 - val_loss: 0.3949
Epoch 15/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8280 - loss: 0.3989 - val_accuracy: 0.8305 - val_loss: 0.3922
Epoch 16/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8393 - loss: 0.3843 - val_accuracy: 0.8355 - val_loss: 0.3895
Epoch 17/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8310 - loss: 0.3917 - val_accuracy: 0.8360 - val_loss: 0.3869
Epoch 18/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8332 - loss: 0.3917 - val_accuracy: 0.8410 - val_loss: 0.3844
Epoch 19/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8389 - loss: 0.3858 - val_accuracy: 0.8430 - val_loss: 0.3820
Epoch 20/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8511 - loss: 0.3707 - val_accuracy: 0.8460 - val_loss: 0.3796
Epoch 21/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8454 - loss: 0.3744 - val_accuracy: 0.8445 - val_loss: 0.3773
Epoch 22/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8409 - loss: 0.3791 - val_accuracy: 0.8465 - val_loss: 0.3751
Epoch 23/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8420 - loss: 0.3731 - val_accuracy: 0.8480 - val_loss: 0.3728
Epoch 24/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8405 - loss: 0.3745 - val_accuracy: 0.8480 - val_loss: 0.3708
Epoch 25/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8432 - loss: 0.3727 - val_accuracy: 0.8500 - val_loss: 0.3687
Epoch 26/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8526 - loss: 0.3594 - val_accuracy: 0.8545 - val_loss: 0.3667
Epoch 27/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8449 - loss: 0.3708 - val_accuracy: 0.8545 - val_loss: 0.3650
Epoch 28/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8503 - loss: 0.3669 - val_accuracy: 0.8550 - val_loss: 0.3632
Epoch 29/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8478 - loss: 0.3640 - val_accuracy: 0.8565 - val_loss: 0.3614
Epoch 30/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8468 - loss: 0.3707 - val_accuracy: 0.8550 - val_loss: 0.3600
Epoch 31/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8535 - loss: 0.3563 - val_accuracy: 0.8550 - val_loss: 0.3585
Epoch 32/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8520 - loss: 0.3535 - val_accuracy: 0.8570 - val_loss: 0.3572
Epoch 33/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8554 - loss: 0.3483 - val_accuracy: 0.8620 - val_loss: 0.3560
Epoch 34/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8577 - loss: 0.3507 - val_accuracy: 0.8600 - val_loss: 0.3549
Epoch 35/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8518 - loss: 0.3605 - val_accuracy: 0.8600 - val_loss: 0.3538
Epoch 36/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8461 - loss: 0.3613 - val_accuracy: 0.8605 - val_loss: 0.3526
Epoch 37/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8539 - loss: 0.3521 - val_accuracy: 0.8610 - val_loss: 0.3518
Epoch 38/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8599 - loss: 0.3426 - val_accuracy: 0.8605 - val_loss: 0.3509
Epoch 39/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8539 - loss: 0.3493 - val_accuracy: 0.8610 - val_loss: 0.3500
Epoch 40/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8597 - loss: 0.3453 - val_accuracy: 0.8615 - val_loss: 0.3494
Epoch 41/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8592 - loss: 0.3428 - val_accuracy: 0.8640 - val_loss: 0.3486
Epoch 42/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8587 - loss: 0.3433 - val_accuracy: 0.8630 - val_loss: 0.3482
Epoch 43/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8556 - loss: 0.3502 - val_accuracy: 0.8640 - val_loss: 0.3474
Epoch 44/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8553 - loss: 0.3498 - val_accuracy: 0.8620 - val_loss: 0.3466
Epoch 45/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8593 - loss: 0.3458 - val_accuracy: 0.8650 - val_loss: 0.3463
Epoch 46/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8536 - loss: 0.3494 - val_accuracy: 0.8610 - val_loss: 0.3459
Epoch 47/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8599 - loss: 0.3442 - val_accuracy: 0.8645 - val_loss: 0.3451
Epoch 48/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8664 - loss: 0.3268 - val_accuracy: 0.8650 - val_loss: 0.3447
Epoch 49/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8606 - loss: 0.3389 - val_accuracy: 0.8640 - val_loss: 0.3445
Epoch 50/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8598 - loss: 0.3411 - val_accuracy: 0.8640 - val_loss: 0.3441
Epoch 51/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8547 - loss: 0.3457 - val_accuracy: 0.8640 - val_loss: 0.3435
Epoch 52/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8538 - loss: 0.3430 - val_accuracy: 0.8655 - val_loss: 0.3432
Epoch 53/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.3431 - val_accuracy: 0.8645 - val_loss: 0.3432
Epoch 54/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8553 - loss: 0.3424 - val_accuracy: 0.8650 - val_loss: 0.3427
Epoch 55/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8632 - loss: 0.3316 - val_accuracy: 0.8640 - val_loss: 0.3425
Epoch 56/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8563 - loss: 0.3418 - val_accuracy: 0.8640 - val_loss: 0.3421
Epoch 57/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8625 - loss: 0.3293 - val_accuracy: 0.8650 - val_loss: 0.3419
Epoch 58/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8612 - loss: 0.3458 - val_accuracy: 0.8635 - val_loss: 0.3414
Epoch 59/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8558 - loss: 0.3470 - val_accuracy: 0.8630 - val_loss: 0.3412
Epoch 60/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8592 - loss: 0.3407 - val_accuracy: 0.8660 - val_loss: 0.3407
Epoch 61/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8681 - loss: 0.3327 - val_accuracy: 0.8645 - val_loss: 0.3410
Epoch 62/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8568 - loss: 0.3421 - val_accuracy: 0.8655 - val_loss: 0.3408
Epoch 63/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8632 - loss: 0.3343 - val_accuracy: 0.8640 - val_loss: 0.3403
Epoch 64/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8594 - loss: 0.3315 - val_accuracy: 0.8640 - val_loss: 0.3401
Epoch 65/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8681 - loss: 0.3245 - val_accuracy: 0.8635 - val_loss: 0.3403
Epoch 66/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8619 - loss: 0.3399 - val_accuracy: 0.8630 - val_loss: 0.3398
Epoch 67/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8543 - loss: 0.3487 - val_accuracy: 0.8640 - val_loss: 0.3397
Epoch 68/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8616 - loss: 0.3346 - val_accuracy: 0.8630 - val_loss: 0.3396
Epoch 69/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8617 - loss: 0.3340 - val_accuracy: 0.8635 - val_loss: 0.3393
Epoch 70/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8684 - loss: 0.3243 - val_accuracy: 0.8650 - val_loss: 0.3395
Epoch 71/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8618 - loss: 0.3261 - val_accuracy: 0.8645 - val_loss: 0.3390
Epoch 72/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8627 - loss: 0.3331 - val_accuracy: 0.8660 - val_loss: 0.3386
Epoch 73/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8615 - loss: 0.3361 - val_accuracy: 0.8640 - val_loss: 0.3387
Epoch 74/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8577 - loss: 0.3390 - val_accuracy: 0.8635 - val_loss: 0.3385
Epoch 75/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8565 - loss: 0.3398 - val_accuracy: 0.8650 - val_loss: 0.3378
Epoch 76/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8631 - loss: 0.3370 - val_accuracy: 0.8635 - val_loss: 0.3381
Epoch 77/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8589 - loss: 0.3350 - val_accuracy: 0.8645 - val_loss: 0.3378
Epoch 78/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8616 - loss: 0.3361 - val_accuracy: 0.8655 - val_loss: 0.3373
Epoch 79/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8619 - loss: 0.3355 - val_accuracy: 0.8645 - val_loss: 0.3375
Epoch 80/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8674 - loss: 0.3235 - val_accuracy: 0.8645 - val_loss: 0.3375
Epoch 81/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8622 - loss: 0.3327 - val_accuracy: 0.8660 - val_loss: 0.3379
Epoch 82/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8566 - loss: 0.3395 - val_accuracy: 0.8645 - val_loss: 0.3368
Epoch 83/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8663 - loss: 0.3217 - val_accuracy: 0.8635 - val_loss: 0.3373
Epoch 84/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8697 - loss: 0.3194 - val_accuracy: 0.8625 - val_loss: 0.3369
Epoch 85/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8624 - loss: 0.3290 - val_accuracy: 0.8665 - val_loss: 0.3369
Epoch 86/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8586 - loss: 0.3375 - val_accuracy: 0.8640 - val_loss: 0.3364
Epoch 87/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8586 - loss: 0.3395 - val_accuracy: 0.8640 - val_loss: 0.3361
Epoch 88/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8607 - loss: 0.3357 - val_accuracy: 0.8660 - val_loss: 0.3362
Epoch 89/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8632 - loss: 0.3335 - val_accuracy: 0.8655 - val_loss: 0.3363
Epoch 90/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8637 - loss: 0.3309 - val_accuracy: 0.8660 - val_loss: 0.3364
Epoch 91/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8659 - loss: 0.3251 - val_accuracy: 0.8670 - val_loss: 0.3363
Epoch 92/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8655 - loss: 0.3313 - val_accuracy: 0.8665 - val_loss: 0.3363
Epoch 93/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8619 - loss: 0.3319 - val_accuracy: 0.8640 - val_loss: 0.3357
Epoch 94/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8632 - loss: 0.3296 - val_accuracy: 0.8650 - val_loss: 0.3356
Epoch 95/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8589 - loss: 0.3417 - val_accuracy: 0.8655 - val_loss: 0.3361
Epoch 96/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8661 - loss: 0.3273 - val_accuracy: 0.8670 - val_loss: 0.3354
Epoch 97/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8690 - loss: 0.3162 - val_accuracy: 0.8660 - val_loss: 0.3351
Epoch 98/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8661 - loss: 0.3227 - val_accuracy: 0.8645 - val_loss: 0.3353
Epoch 99/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8587 - loss: 0.3342 - val_accuracy: 0.8650 - val_loss: 0.3346
Epoch 100/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8690 - loss: 0.3232 - val_accuracy: 0.8655 - val_loss: 0.3351

In [134]:
data.shape

(10000, 11)

In [163]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [165]:
%reload_ext tensorboard

In [166]:

%tensorboard --logdir logs/fit --port=6007

Reusing TensorBoard on port 6007 (pid 24232), started 0:00:32 ago. (Use '!kill 24232' to kill it.)